workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: ðŸ” Check Flutter environment
        script: flutter doctor -v

      - name: ðŸ“¦ Install dependencies
        script: flutter pub get

      - name: ðŸ§¹ Clean previous builds
        script: flutter clean

      - name: ðŸ”§ Create Podfile with correct post_install
        script: |
          cd ios
          cat > Podfile <<'EOF'
          platform :ios, '10.0'

          target 'Runner' do
            use_frameworks!
            use_modular_headers!

            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

            post_install do |installer|
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
                end
              end
            end
          end
          EOF
          pod install
          cd ..

      - name: ðŸ—ï¸ Build iOS app for Simulator
        script: flutter build ios --simulator --debug

      - name: ðŸ“ Package Runner.app into .zip
        script: |
          mkdir -p build/ios/ipa
          zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app

    artifacts:
      - build/ios/ipa/Runner.app.zip
