// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBLSpe3NjquEVtzvY8wXFFxt1ZAKl6ToU',
    appId: '1:681645922454:web:4a52b8abe60f96406f8ab7',
    messagingSenderId: '681645922454',
    projectId: 'food-diary-app-c6bf0',
    authDomain: 'food-diary-app-c6bf0.firebaseapp.com',
    storageBucket: 'food-diary-app-c6bf0.firebasestorage.app',
    measurementId: 'G-81ZSLX0N6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATP085JSDYqDihUPZtbA7Ho2oMRqjaKqU',
    appId: '1:681645922454:android:e4e2cd69109b4e626f8ab7',
    messagingSenderId: '681645922454',
    projectId: 'food-diary-app-c6bf0',
    storageBucket: 'food-diary-app-c6bf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_WF5ih9WPqozfnVRMVXvPTc3qovlpO9o',
    appId: '1:681645922454:ios:d3d3a443eab69a236f8ab7',
    messagingSenderId: '681645922454',
    projectId: 'food-diary-app-c6bf0',
    storageBucket: 'food-diary-app-c6bf0.firebasestorage.app',
    iosBundleId: 'com.example.fooddiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_WF5ih9WPqozfnVRMVXvPTc3qovlpO9o',
    appId: '1:681645922454:ios:d3d3a443eab69a236f8ab7',
    messagingSenderId: '681645922454',
    projectId: 'food-diary-app-c6bf0',
    storageBucket: 'food-diary-app-c6bf0.firebasestorage.app',
    iosBundleId: 'com.example.fooddiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBLSpe3NjquEVtzvY8wXFFxt1ZAKl6ToU',
    appId: '1:681645922454:web:1ee4b0592ff58daa6f8ab7',
    messagingSenderId: '681645922454',
    projectId: 'food-diary-app-c6bf0',
    authDomain: 'food-diary-app-c6bf0.firebaseapp.com',
    storageBucket: 'food-diary-app-c6bf0.firebasestorage.app',
    measurementId: 'G-DS6V9CDTD9',
  );
}
